### PR TITLE
Using Disba as a solver instead of legacy Fortran routines

### PR DESCRIPTION
**Pull request by th-reb**
1. Replace calls to the legacy Fortran routines with Disba API
2. Unit conversion (m in km, density in g/cm^3)
3. Choose between phase or group dispersion curves using the Disba wrapper

ISSUE: Love wave inversion fails without notice.

### CODE REVIEW

**Comment by th-reb** [comment]
Converted the example dataset.
Example runs fast (~1 second) on Rayleigh waves and single CPU. 
Love inversion still fail for some reason.

MPI not working.

**Comment by th-reb** [comment]
@keurfonluu If you have time to look, what would be your advice for the MPI parallelization?

**Comment by keurfonluu** [comment]
Nice! Thanks for the PR.

For MPI, there shouldn't be too much to do since it is mostly handled by `stochopy`. The Python script should just prepare the communication and tells `stochopy` to run with MPI (as it is already done in the sample script). What isn't working?

**Comment by th-reb** [comment]
> Nice! Thanks for the PR.
> 
> For MPI, there shouldn't be too much to do since it is mostly handled by `stochopy`. The Python script should just prepare the communication and tells `stochopy` to run with MPI (as it is already done in the sample script). What isn't working?

Indeed, it's working, thanks. I was doing a wrong mpiexec call...

**Comment by th-reb** [comment]
"Working" example added in 2915fbb.
However, it is somewhat unstable for some reason. It can stuck randomly on a run in case of inadequate initialization.
In this case, relaunching the script works fine.

Stille some work to do to fix this behaviour and the Love inversion, but I think it should be done in a new PR.

**Pull request merged**
